### Numpy Array and Basics
learn about numpy 

In [2]:
import numpy as np

### Creating array from list

In [7]:
array_1d = np.array([1,2,3,4,5])
print("1D array: ", array_1d)

array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", array_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy Array

In [3]:
py_list = [1,2,3]
print("Multiplication of Python List: ", py_list*2)
np_array = np.array([1,2,3])
print("Multiplication of Numpy Array: ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List Operation Time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy Operation Time: ", time.time() - start)




Multiplication of Python List:  [1, 2, 3, 1, 2, 3]
Multiplication of Numpy Array:  [2 4 6]

 List Operation Time:  0.3061790466308594

 Numpy Operation Time:  0.017859458923339844


### Creating Array from Scratch

In [6]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

ones = np.ones((2,3))
print("ones array: \n", ones)

full = np.full((2,2),6)
print("full array: \n", full)

random = np.random.random((2,3))
print("Random Array: \n", random)

sequence = np.arange(0,10,2)
print("Sequence Array: \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[6 6]
 [6 6]]
Random Array: 
 [[0.12841809 0.79866998 0.53386132]
 [0.30123587 0.49633901 0.50469564]]
Sequence Array: 
 [0 2 4 6 8]


### Vector , Matrix and Tensor

In [11]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2],[3,4]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[4,5],[6,7]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2]
 [3 4]]
Tensor:  [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


### Array Properties

In [16]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape: ", arr.shape )
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("dType: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
dType:  int64


### Array Reshaped

In [26]:
arr = np.arange(12)
print("Original Array: ", arr)

#Reshape
reshaped = arr.reshape((3,4))
print("Reshaped: \n", reshaped)

#Flatten
flattened = reshaped.flatten()
print("Flatten: ", flattened)


#Ravel (return view , instead of Copy)
ravel = reshaped.ravel()
print("Ravel: ", ravel)

#Transpose
transpose = reshaped.T
print("Transpose: ", transpose)

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
