### Numpy Array operations

In [2]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing: ", arr[2:7])
print("With Steps: ", arr[1:8:2])
print("Negative Indexing: ", arr[-3])

Basic Slicing:  [3 4 5 6 7]
With Steps:  [2 4 6 8]
Negative Indexing:  8


In [11]:
arr_2d = np.array([[1,2,3],
                   [3,4,5],
                   [6,7,8]])
print("Specific element: ", arr_2d[2,1])
print("Entire Row: ", arr_2d[1])
print("ENtire column:", arr_2d[:,1] )

Specific element:  7
Entire Row:  [3 4 5]
ENtire column: [2 4 7]


### Sorting

In [19]:
unsorted = np.array([2,1,6,4,3,5])
print("Sorted 1D array: ", np.sort(unsorted))
unsorted = np.array([[2,1],[3,2],[1,3]])
print("Sorted 2D Array by Column: ", np.sort(unsorted, axis=0))

Sorted 1D array:  [1 2 3 4 5 6]
Sorted 2D Array by Column:  [[1 1]
 [2 2]
 [3 3]]


### Filter

In [24]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
odd_number = numbers[numbers % 2 != 0 ]
print("Even Numbers : ", even_number)
print("Odd Numbers : ", odd_number)

Even Numbers :  [ 2  4  6  8 10]
Odd Numbers :  [1 3 5 7 9]


### Filter With Mask

In [26]:
mask = numbers > 5
print("Number Greater than 5: ", numbers[mask])

Number Greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing Vs Np.Where()

In [30]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result)
print("Np Where: ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np Where:  [ 6  7  8  9 10]


In [40]:
condition_array = np.where(numbers>5, numbers*4 , numbers)
condition_array1 = np.where(numbers>5, True , False)
print(condition_array)
print(condition_array1)

[ 1  2  3  4  5 24 28 32 36 40]
[False False False False False  True  True  True  True  True]


### Adding and Removing Data

In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [44]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])
print("Compatibility Shape :", a.shape == b.shape)


Compatibility Shape : False


In [52]:
original = np.array([[1,2],[3,4]])
print("Original:\n", original)
new_row = np.array([5,6])
with_new_row = np.vstack((original,new_row))
print("Add new Row: \n",with_new_row)
new_column = np.array([[3],[5]])
With_new_Column = np.hstack((original,new_column))
print("Add New Column: \n", With_new_Column)


Original:
 [[1 2]
 [3 4]]
Add new Row: 
 [[1 2]
 [3 4]
 [5 6]]
Add New Column: 
 [[1 2 3]
 [3 4 5]]


In [54]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("Array After Deletion : ",deleted)

Array After Deletion :  [1 2 4 5]
